name: train-and-push

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # every day at 02:00 UTC

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: iterative/setup-dvc@v2

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      # ---- removed: dvc pull (we retrain fresh models locally) ----

      - name: Run pipeline
        run: python main.py

      - name: Track updated artifacts
        run: dvc add models/occupancy models/rewards models/pricing metrics

      - name: Push artifacts to DVC remote
        run: dvc push

      - name: Commit updated DVC pointers
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add \
            models/occupancy.dvc \
            models/rewards.dvc \
            models/pricing.dvc \
            metrics.dvc
          git commit -m "chore: update models & metrics [skip ci]" || echo "No pointer changes"
          git push origin main
